### ISSUE TITLE
Add SLiM models validation plots to supplement

### ISSUE THREAD

**Issue by jeromekelleher** [popgensims/manuscript#150] opened 2020-03-17 18:04 UTC
We want some sort of validation that the SLiM engine and msprime engine are doing more-or-less the same thing. For the supplement, I guess we'd want a plot of some summary stat(s), and show the effect of 

- scaling factor
- recapitation/running for 10N gens

It'll be quite a nice plot if we can show that with different scaling factors we converge on the same result as msprime, and that using recapitation gets the same answer, but is massively faster than running for 10N generations.

There's probably quite a lot we could explore here.

Also, given that the SLiM engine code is reasonably complex, we probably want to be able to repeat something like this as statistical tests in stdpopsim.

**Comment by jeromekelleher** [comment] 2020-03-17 18:08
@jradrion kindly volunteered to help out with this. Have you any thoughts on what would be a nice figure to aim for Jeff?

**Comment by jradrion** [comment] 2020-03-17 18:32
@jeromekelleher Perhaps, a set of Q-Q plots in a multi-panel figure showing a few key summary stats with a few different scaling factors? We might also want runtime comparisons?

**Comment by grahamgower** [comment] 2020-03-17 18:44
+1 for basic runtime comparisons.

**Comment by jeromekelleher** [comment] 2020-03-17 18:52
> @jeromekelleher Perhaps, a set of Q-Q plots in a multi-panel figure showing a few key summary stats with a few different scaling factors? We might also want runtime comparisons?

Sounds great. The run time thing will be interesting since we're using recapitation, model scaling etc.

**Comment by andrewkern** [comment] 2020-03-17 21:20
Would be great if we got some publication quality figs out of this @jradrion. I think these will be very interesting comparisons.

**Comment by jradrion** [comment] 2020-03-17 23:10
Good deal, I'll get on it!

**Comment by jradrion** [comment] 2020-03-19 17:22
I was thinking about something like the following for a figure:
![slim_supp_plot](https://user-images.githubusercontent.com/20053488/77094883-58a8f700-69ca-11ea-98e6-8bb678877754.png)
distributions would be from windows along human chr 21 & HapMapII_GRCh37 run under Africa_1T12. Runtimes distributions would be from simulation reps (if it's not too slow) or point estimates if things are really slow. Does this sound like a plan? I'm open to suggestions

**Comment by jeromekelleher** [comment] 2020-03-19 17:28
Cool, I like it!

**Comment by grahamgower** [comment] 2020-03-20 07:48
That looks really nice @jradrion. I've started working on some validation code. I'll try to generalise it a little so that it will be straightforward for you to hack on the plotting code and get it how you like it.

**Comment by jradrion** [comment] 2020-03-20 16:24
Wow, thanks @grahamgower! That sounds great, I appreciate it! Just now I tried my first test run with the SLiM engine and got the following error. I'm sure it's a simple setup mistake on my end, and I have not attempted to debug yet, but if you've seen this one before and have any suggestions, I'm all ears. Time to make a some coffee and try to get this running... 
```
Traceback (most recent call last):
  File "/home/jadrion/miniconda3/envs/stdpopsim/bin/stdpopsim", line 11, in <module>
    load_entry_point('stdpopsim==0.1.2.dev46+gfb96f1c', 'console_scripts', 'stdpopsim')()
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/stdpopsim-0.1.2.dev46+gfb96f1c-py3.7.egg/stdpopsim/cli.py", line 616, in stdpopsim_main
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/stdpopsim-0.1.2.dev46+gfb96f1c-py3.7.egg/stdpopsim/cli.py", line 607, in run
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/stdpopsim-0.1.2.dev46+gfb96f1c-py3.7.egg/stdpopsim/cli.py", line 424, in run_simulation
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/stdpopsim-0.1.2.dev46+gfb96f1c-py3.7.egg/stdpopsim/slim_engine.py", line 639, in simulate
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/pyslim/slim_tree_sequence.py", line 29, in load
    ts = SlimTreeSequence.load(path)
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/pyslim/slim_tree_sequence.py", line 179, in load
    return cls(ts, reference_sequence)
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/pyslim/slim_tree_sequence.py", line 102, in __init__
    provenance = get_provenance(ts)
  File "/gpfs/home/jadrion/miniconda3/envs/stdpopsim/lib/python3.7/site-packages/pyslim/provenance.py", line 34, in get_provenance
    raise ValueError("Tree sequence contains no SLiM provenance entries.")
ValueError: Tree sequence contains no SLiM provenance entries.
```
actually just now noticing that the `.trees` file was not created, so that could be the part of the problem...

**Comment by grahamgower** [comment] 2020-03-20 16:30
I saw this yesterday actually. I think there might be something funny going on with bleeding-edge versions of tskit and/or pyslim. I haven't had time to identify it further. I uninstalled tskit, pyslim, and msprime (which were the latest git master) and reinstalled from pip and the message went away.

If you can figure out which library is the culprit, and git bisect back to the change, that would be amazing!

**Comment by jradrion** [comment] 2020-03-20 16:31
OK, sounds like a good lead. I'll look into it.

**Comment by jradrion** [comment] 2020-03-20 18:24
@grahamgower when you get the chance could you send me your `pip list` / `conda list` so I can compare versions? I've tried all combinations of tskit {0.2.3, 0.2.2, 0.2,1, 0.1.5} and pyslim {0.314, 0.312, 0.311, 0.31, 0.1} and keep getting the same error. I also uninstalled tskit, pyslim, and msprime, and reinstalled all from pip and I continue to have the same issue.

**Comment by grahamgower** [comment] 2020-03-20 19:17
Sorry if I sent you on a wild goose chase! Maybe its a different package? Attached is my current `pip list` output; I don't have conda. My python version is  3.8.2.
[pip-list.txt](https://github.com/popsim-consortium/manuscript/files/4361465/pip-list.txt)

**Comment by jradrion** [comment] 2020-03-20 19:42
No worries! 
Awesome, thank you @grahamgower!

**Comment by grahamgower** [comment] 2020-03-20 20:02
@jradrion, I can reproduce the issue when I install msprime from git master. Quite strange.

I installed it from the git checkout with `python setup.py develop --user`.
```
$ pip list | grep msprime
msprime                       0.7.5.dev93+nged4879a           /home/grg/src/msprime
```

**Comment by grahamgower** [comment] 2020-03-20 20:06
I bet it has something to do with this warning triggered by pyslim:
```
/home/grg/src/msprime/msprime/simulations.py:931: UserWarning: num_loci is no longer supported and should not be used.
```

**Comment by jradrion** [comment] 2020-03-20 22:11
Oddly I don't get that particular warning. 

I've now set all of my package versions to what you are using with the exception of stdpopsim itself and still no luck. I've tried the following stdpopsim versions:
`0.1.1`
`0.1.2.dev48+ng80e5233`

I'll keep at it.

**Comment by jeromekelleher** [comment] 2020-03-23 09:03
@jradrion, are you using the bleeding edge version of SLiM by any chance? You might be experiencing fall out from this: https://github.com/tskit-dev/pyslim/issues/67#issuecomment-601475902

**Comment by jeromekelleher** [comment] 2020-03-23 09:04
I would stay away from the bleeding edge msprime unless you have to use it, we've been making big changes in the run up to 1.0 and have likely broken things. That ``num_loci`` warning above from pyslim is one of these things.

**Comment by jradrion** [comment] 2020-03-23 16:14
@jeromekelleher I've been running SLiM 3.3.2 and msprime 0.7.4. Is there a particular SLiM version I should consider rolling back to?

**Comment by grahamgower** [comment] 2020-03-23 16:24
@jradrion can you double check the msprime version in your environment? E.g.
```
>>> import msprime
>>> msprime.__version__
'0.7.4'
```
Its suprisingly easy to have multiple installations of a package hanging around, and often not obvious which is taking precedence in any given case.

**Comment by grahamgower** [comment] 2020-03-23 16:25
PS: I'm running slim 3.3.2, and 3.3.0, on different systems, and both have been working fine.

**Comment by jeromekelleher** [comment] 2020-03-23 16:33
Any recent version of SLiM should be OK, just not bleeding edge master.

**Comment by jradrion** [comment] 2020-03-23 16:33
@grahamgower what is this string?

```
>>> import msprime
\s*(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*[, ]\s*(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*[, ]\s*[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*[, ]\s*[01]\s*[, ]\s*[01]\s*[, ]\s*[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*[, ]\s*[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?\s*
>>> msprime.__version__
'0.7.4'
```

**Comment by grahamgower** [comment] 2020-03-23 16:35
Well that looks like a regex, but I've no idea what its doing there! Maybe time to make a new conda env?

**Comment by jradrion** [comment] 2020-03-23 16:37
> Maybe time to make a new conda env?

Yeah, I think so.

**Comment by petrelharp** [comment] 2020-03-23 17:41
> Tree sequence contains no SLiM provenance entries.

This is usually because your pyslim is not up to date. Unless it's because you installed SLiM from master in the last four days or so, as jerome says, I have to update pyslim (on the list for today!).

**Comment by jradrion** [comment] 2020-03-23 17:43
OK, I've tried a couple of fresh environments now (cleared .local, etc), and I'm still getting the same `ValueError: Tree sequence contains no SLiM provenance entries.`.
I've listed my setup steps in case anything jumps out at you as being especially wrong.

- rm miniconda
- install miniconda
- conda create --yes --name popsim python==3.8
- conda activate popsim
- cd /stdpopsim/
- git pull
- pip install -r ./requirements/development.txt (also tried with conda-minimal.txt)
- python setup install

`slim -ts` returns: `SUCCESS count: 69142`

The traceback suggests to be that the .trees file should have been written somewhere by this step, no? However, no .trees file is ever written.
```
  File "/home/jadrion/miniconda3/envs/popsim/lib/python3.8/site-packages/pyslim-0.314-py3.8.egg/pyslim/slim_tree_sequence.py", line 29, in load
    ts = SlimTreeSequence.load(path)
```

**Comment by jradrion** [comment] 2020-03-23 17:45
@petrelharp My SLiM install is relatively recent, I think I cloned the github repo last Thursday or Friday. I'm using pyslim 0.314, if that helps.

**Comment by jradrion** [comment] 2020-03-23 18:12
OK, so this is possibly all due to me recently compiling SLiM from master. Thanks for your help, all.

**Comment by petrelharp** [comment] 2020-03-23 20:52
You can easily check by reverting to the last tagged release.

**Comment by jradrion** [comment] 2020-03-23 21:09
@petrelharp Yep, everything is working for me now!

**Comment by petrelharp** [comment] 2020-03-25 17:07
I updated pyslim, btw, so this should work with the latest SLiM now.

**Comment by jradrion** [comment] 2020-03-25 17:16
Awesome, thanks @petrelharp

**Comment by jradrion** [comment] 2020-03-26 00:26
![popsim_slim_val](https://user-images.githubusercontent.com/20053488/77597542-725fa800-6ebc-11ea-8f9f-355193d7ef5b.png)
OK, perhaps something that looks a bit like this? This is a small test run on _CanFam_ under constant pop size. I can work on the plot specifics to improve the overall look (thoughts/suggestions?), but do we also want to present more data? @grahamgower's validation script auto-generates a number of other stats that might be worth including, but large multi-panel plots may quickly become overwhelming.

**Comment by andrewkern** [comment] 2020-03-26 00:29
this looks great to me. why not do this for a couple human models, flies, arabidopsis, and CanFam?

**Comment by jradrion** [comment] 2020-03-26 00:40
@andrewkern sounds good!

**Comment by petrelharp** [comment] 2020-03-26 01:15
Looks real nice. But, just to be clear, what exactly are the points in those plots?  I'm guessing those are q-q plots of the values across windows?  If so: great validation.

**Comment by petrelharp** [comment] 2020-03-26 01:17
Were the models run long enough that you'd think you'd need recapitation?

**Comment by jradrion** [comment] 2020-03-26 03:27
> Looks real nice. But, just to be clear, what exactly are the points in those plots? I'm guessing those are q-q plots of the values across windows? If so: great validation.

They are the qth quantiles of the value of each statistic across replicate simulations, not windows. We could plot across windows, but I used the validation script on the repo as a framework, and my reading of that script is that a single value is returned per tree sequence.

> Were the models run long enough that you'd think you'd need recapitation?

I'm not sure. I'm not familiar enough with SLiM to know when one would necessarily _need_ recapitation. I had planned to show recapitation regardless. Perhaps the comparisons will be more appropriate with other species/models?

**Comment by petrelharp** [comment] 2020-03-26 04:01
Well, I say none of the plots should show wrong simulations (eg no recapitation if it needs it), and only show "recapitation" as a point of comparison if it is a meaningful comparison (eg we simulated a big N for a small time and recapitated).

To recall, one should probably always recapitate by default, just in case of uncoalesced trees. But if the simulation is coalesced it won't take hardly any work. Recapitation becomes a strategy if you use it to do most of your sim with msprime, and only recent history with something non-coalescent based.

**Comment by grahamgower** [comment] 2020-03-26 06:38
If we want to show QQ plots without recapitation, we will need to close this issue first (opinions/expertise wanted!): https://github.com/popsim-consortium/stdpopsim/issues/420

The validation script currently simulates ~250kb region, and @jradrion is correct that each statistic is calculated once for each replicate. My motivation here is that it's far quicker to do many replicates at this size in parallel, than to do a single replicate of a longer region. Is there a compelling reason to calculate statistics on windows of longer contigs?

Also please note that any simulation with a single population of constant size has zero `msprime.DemographicEvent`s. This means that SLiM does nothing except the burn-in phase. Unless you're doing recapitation, in which case SLiM exits after creating the first generation individuals. I.e. the QQ plots in the lower panel are effectively showing msprime vs. msprime. This is useful to catch bugs in how the slim engine does recapitation, but maybe not appropriate for the manuscript.

**Comment by jeromekelleher** [comment] 2020-03-26 09:02
This looks great, thanks @jradrion! One thing we are missing though is whether we're capturing LD properly. What if we replace segsites or pi with num_trees? In practise num_trees is a very good way of making sure recombination is being done properly.

**Comment by jeromekelleher** [comment] 2020-03-26 09:03
Totally agree we don't want too many stats btw, I think the layout is just right now.

**Comment by jradrion** [comment] 2020-03-26 16:55
@petrelharp 
> Well, I say none of the plots should show wrong simulations (eg no recapitation if it needs it), and only show "recapitation" as a point of comparison if it is a meaningful comparison (eg we simulated a big N for a small time and recapitated).

Sure, I think this makes sense. So, if we want to present a plot similar to the above, we should try to find an example that meets both of these conditions, correct? 

One thing I think would be helpful, is documentation about which SLiM-engine options are appropriate for each model. For example, as a novice, I'd be tempted to simply use `-e slim` alone and use the defaults for all other options. If this is not appropriate for any particular model, or likewise if using `--slim_no_recapitation` is inappropriate for any model because we know that the trees won't coalesce without it, we might want to present users with a warning message.


@grahamgower 
> If we want to show QQ plots without recapitation, we will need to close this issue first (opinions/expertise wanted!): popsim-consortium/stdpopsim#420

I'll comment directly to that issue, but I like your suggestion of using `--slim-burnin 0` for no burnin.

> I.e. the QQ plots in the lower panel are effectively showing msprime vs. msprime. 

Thank you for pointing this out, I had not considered that. I think the plan for a manuscript figure would be to show comparisons under a demographic model, so this should not be an issue going forward, correct?


@jeromekelleher 
> What if we replace segsites or pi with num_trees?

Sounds like a plan, my preference would be to replace segregating_sites, but only because the definition for that statistic is somewhat unclear to me. Initially I had assumed it was akin to theta S, but the definition reads, "Computes the density of segregating sites for each of the sets of nodes from sample_sets, and related quantities." Can you give me an intuition for what that means? I'm still a little confused.

**Comment by grahamgower** [comment] 2020-03-26 17:00
> Thank you for pointing this out, I had not considered that. I think the plan for a manuscript figure would be to show comparisons under a demographic model, so this should not be an issue going forward, correct?

Yeah, that's probably fine. If recapitation is enabled, the slim part of the simulation will start from the root of the population tree/graph.

**Comment by jradrion** [comment] 2020-03-26 17:03
@grahamgower just to be clear though, I should probably hold-off on spooling up demographic simulations until popsim-consortium/stdpopsim#420 is resolved?

**Comment by grahamgower** [comment] 2020-03-26 17:04
Yeah, otherwise you might have to rerun them!

**Comment by jeromekelleher** [comment] 2020-03-26 19:58
> Sounds like a plan, my preference would be to replace segregating_sites, but only because the definition for that statistic is somewhat unclear to me. Initially I had assumed it was akin to theta S, but the definition reads, "Computes the density of segregating sites for each of the sets of nodes from sample_sets, and related quantities." Can you give me an intuition for what that means? I'm still a little confused.

I think it's just the average number of segregating sites in the default case, nothing particularly fancy.

**Comment by jradrion** [comment] 2020-03-26 20:11
OK, makes sense, thanks.

**Comment by jradrion** [comment] 2020-03-26 23:07
I went ahead an simulated with recapitation because it's pretty quick. Here is my first run (100 reps, 20 samples) of human chr22 w/ HapMapII_GRCh37 under Africa1T12...
![popsim_slim_val_demographicModel](https://user-images.githubusercontent.com/20053488/77704535-8538b200-6f7a-11ea-8b13-e87b2e9c2437.png)

**Comment by andrewkern** [comment] 2020-03-26 23:08
very cool. now can you do this with a variable number of burn-in generations?

**Comment by jradrion** [comment] 2020-03-26 23:13
> very cool. now can you do this with a variable number of burn-in generations?

I believe I need to wait for popsim-consortium/stdpopsim#420 to experiment with burn in

**Comment by petrelharp** [comment] 2020-03-26 23:31
Minor point: the y-axes on the Runtime plots need to start at 0.

**Comment by jradrion** [comment] 2020-03-27 17:56
Curiosity got the best of me so I sent out some more sims, again this is 100 reps of human chr22 w/ HapMapII_GRCh37 under Africa1T12. The no-recap sims with Q=1 are about to run out of walltime, so I probably won't have those for a couple of days.
![popsim_slim_val_demographicModel](https://user-images.githubusercontent.com/20053488/77804300-6e5a9400-703c-11ea-83e6-f20b96533d6c.png)

**Comment by andrewkern** [comment] 2020-03-27 22:39
super cool @jradrion

**Comment by jeromekelleher** [comment] 2020-03-30 08:15
Very cool indeed. Looks like we have issues with recapitation @grahamgower, or do we already know this?

**Comment by grahamgower** [comment] 2020-03-30 08:26
I'm not sure what's going on here with recapitaiton---I don't think we saw anything like this before anyway. These are 25 mb sims, and I've only done 250 kb so far. Maybe longer contigs trigger this difference?

**Comment by grahamgower** [comment] 2020-03-30 09:00
Oh, I see what's going on here. This is with HapMapII_GRCh37, and the recapitation is just using a uniform map. This will also be visible for some demographic models with `--slim-burn-in 0` after https://github.com/popsim-consortium/stdpopsim/pull/450 is applied.

**Comment by jeromekelleher** [comment] 2020-03-30 09:10
This shouldn't affect the ``num_trees`` distribution though, should it? We should have the same overall rate of recombination, it's just the breakpoints will happen at different places (unless we have super intense hotspots where lots of breaks happen independently at exactly the same base).

Unless the rate of recombination we have on the uniform map is significantly different to the average of HapMapII_GRCh37?

**Comment by grahamgower** [comment] 2020-03-30 09:15
The rate for the uniform map is `recomb_map.mean_recombination_rate`, where recomb_map will be HapMapII_GRCh37. From those plots it just looks like the variance in the number of trees is different.

**Comment by jeromekelleher** [comment] 2020-03-30 09:20
> From those plots it just looks like the variance in the number of trees is different.

True, but the point still holds. There shouldn't be any difference in distribution in the number of trees unless we get multiple recombination hits at the same point (which is quite possible, I guess)

**Comment by grahamgower** [comment] 2020-03-30 12:43
Well whatever is going on, its a problem with the msprime engine too.
[hapmap__uniform.pdf](https://github.com/popsim-consortium/manuscript/files/4402744/hapmap__uniform.pdf)

"hapmap" is `stdpopsim HomSap 100 -c chr22 -g HapMapII_GRCh37`
"uniform" is `stdpopsim HomSap 100 -c chr22`

**Comment by jeromekelleher** [comment] 2020-03-30 14:34
Hmm, it's probably the massive chunks that have a single tree (like the centromere) that we hit before. We never did get around to putting in the automasking stuff.

**Comment by andrewkern** [comment] 2020-03-30 16:00
not sure we would want to automask in this case anyway. 

@grahamgower num_sites here is the number of segregating sites? it looks like the uniform case is always returning nearly the same number

**Comment by grahamgower** [comment] 2020-03-30 16:48
@andrewkern I always thought that the num_sites tree sequence property was the number of segregating sites, until I started looking at these plots. Now I'm all kinds of confused. @jeromekelleher can you educate us?

**Comment by petrelharp** [comment] 2020-03-30 17:40
`num_sites` is the number of sites at which we have information about genotypes. They aren't necessarily polymorphic among the samples: they might have a mutation that is fixed among the samples, or might have no mutations at all. Most workflows won't get you sites of the second class (sites with no mutations), but it's easy to get the first one.

**Comment by petrelharp** [comment] 2020-03-30 17:51
Have a look at the allele frequencies, with this code: https://github.com/tskit-dev/tskit/issues/504

**Comment by RyanGutenkunst** [comment] 2020-03-31 02:45
Popping in late... I'm curious about num_trees... Is it connected to some more familiar population-genetic quantity? I don't know how to interpret the changes in num_trees with different scaling without some intuition about the statistic.

**Comment by grahamgower** [comment] 2020-03-31 06:24
The number of recombination breakpoints (in ancestral material).

**Comment by jeromekelleher** [comment] 2020-03-31 07:45
> The number of recombination breakpoints (in ancestral material).

Not quite. It's  the number of *successful* recombination events, i.e. those that result in distinct trees in the output. Some recombinations result in "diamonds" in the ARG, where a common ancestor event immediately puts back together the two lineages that a recombination split up. Msprime/tskit.simplify() will merge together adjacent identical trees, so these events are not counted.

For larger sample sizes it's pretty close to the number of recombinations in ancestral material though.

**Comment by RyanGutenkunst** [comment] 2020-03-31 14:53
I think we should focus on statistics that are calculable from the final sample of the population, without knowing the full simulated history. That seems more relevant to the common use cases of the resource. Is num_trees something we could calculate from the final sample? If not, maybe we should pick something else. I'm not sure what's best. Maybe since we're simulating short stretches, something like r^2 between the first and last or middle and last SNPs?

**Comment by petrelharp** [comment] 2020-03-31 15:50
> I think we should focus on statistics that are calculable from the final sample of the population

I agree - from the *genotypes*. I think looking at these other metrics is informative, and I'm glad to look at them, but mostly to us - we should keep them out of the paper.

**Comment by jeromekelleher** [comment] 2020-03-31 16:09
Sure, for the paper I agree. But for just validating and development having num_trees is really helpful, as we do want to compare the actual tree sequences.

**Comment by jradrion** [comment] 2020-04-02 18:25
I'd like to double check that the plan is indeed to create validation plots similar to the above (although maybe with something other than number_trees?) using a single human chromosome with recombination map (chr22) under AncientEurasia_9K19, correct? There was also mention of using a uniform map. It seems reasonable to have a look at both, if possible.

As an update: I've been running into OOM errors attempting the above (chr22 /w map under AncientEurasia_9K19, Q=10). The errors occurred during the computing of LD, so I should at least get a runtime estimate if I leave out the LD calculation (at least for the moment). Unfortunately, I still don't have a runtime estimate for a simulation with a map. Runtimes are ~3 hours for a 250kb chromosome with no map (Q=1).

**Comment by grahamgower** [comment] 2020-04-02 18:49
> I've been running into OOM errors attempting the above (chr22 /w map under AncientEurasia_9K19, Q=10). The errors occurred during the computing of LD

Oooh, nasty. I reckon it's because I only tested with short 250kb segments. Could you try this (untested) change?

```
diff --git a/validation.py b/validation.py
index deebdbe..5d39538 100755
--- a/validation.py
+++ b/validation.py
@@ -454,11 +454,14 @@ def pairwise_pop_stats(ts):
     return stats
 
 
-def linkage_disequilibrium(ts, span=40000, bins=20, min_obs_per_bin=8):
+def linkage_disequilibrium(
+        ts, span=40000, bins=20, min_obs_per_bin=8, max_sequence_length=1e6):
     """
     R^2 as a function of site-separation distance, for `bins` bins up to a
     site-separation distance of `span` bp.
     """
+    if ts.sequence_length > max_sequence_length:
+        ts = ts.keep_interval([(0, max_seq_length)], record_provenance=False)
     position = [site.position for site in ts.sites()]
     num_sites = len(position)
     assert num_sites == int(ts.num_sites)
```

**Comment by jradrion** [comment] 2020-04-02 18:51
@grahamgower sure thing, thanks

**Comment by jradrion** [comment] 2020-04-02 21:07
Thanks, @grahamgower. Everything is good to go now. The only issue was that `ts = ts.keep_interval([(0, max_seq_length)], record_provenance=False)` should be `ts = ts.keep_intervals([(0, max_sequence_length)], record_provenance=False)`

**Comment by jradrion** [comment] 2020-04-03 22:56
Here are some updated figs for AncientEurasia_9K19, chr22, with a recombination map:
![AE9K19_chr22_map_AI](https://user-images.githubusercontent.com/20053488/78410902-b04a8380-75c2-11ea-89f5-d78ef22aa7e5.png)


and without a map:
![AE9K19_chr22_nomap_AI](https://user-images.githubusercontent.com/20053488/78410906-b5a7ce00-75c2-11ea-80d6-fd5dd7fc0d7f.png)

I'm not sure what might be going on with Q=50/uniform map, thoughts?

**Comment by petrelharp** [comment] 2020-04-04 01:36
In that model some of the populations sizes are very small - e.g. Neanderthal, 86.9. I'm surprised this even *runs* with a SLiM simulation at Q=50, since that'll round to either N=1 or N=2. Oh, I guess that it could run at N=1 because it's an asexual WF simulation? (ps. shouldn't these be sexual populations?)

But, the basic idea why these should differ is that the equivalence rests on the approximation that
```
(1 - 1/N)^t ~ exp(-Nt)
```
which is not so good for small N.

**Comment by petrelharp** [comment] 2020-04-04 03:53
>  (ps. shouldn't these be sexual populations?)

Please ignore this can of worms.

**Comment by andrewkern** [comment] 2020-04-04 05:00
but why the difference between uniform and the hapmap recombination maps? that doesn't make sense to me

**Comment by petrelharp** [comment] 2020-04-04 05:56
> but why the difference between uniform and the hapmap recombination maps? that doesn't make sense to me

Oh, good question. No idea.

**Comment by petrelharp** [comment] 2020-04-14 15:09
The proposed figure looks great, @jradrion - could you put it in the supplement, and maybe a few words about it?

**Closed as completed** 2020-04-27 14:16 UTC
